### ISSUE TITLE
[KIALI-1700] Move const loginHeaders to config.ts

### ISSUE THREAD

**Issue by aljesusg** [kiali/hacktoberfest18#10]
Move the const loginHeaders https://github.com/kiali/kiali-ui/blob/a35c50231cb5e29f7756b857db01809714029b7f/src/services/Api.ts#L24

to the config file https://github.com/kiali/kiali-ui/blob/master/src/config.ts

JIRA: [KIALI-1700](https://issues.jboss.org/browse/KIALI-1700)

**Comment by vanillaSlice** [comment]
I can pick this one up

**Comment by aljesusg** [comment]
closed by https://github.com/kiali/kiali-ui/pull/733
